CREATE TABLE SESSION_TRANSACTION_LINK (
    SESSION_TRANSACTION_HKEY text NOT NULL,
    SESSION_HKEY text NOT NULL,
    TRANSACTION_HKEY text NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE text NOT NULL,

    CONSTRAINT PK_SESSION_TRANSACTION_LINK PRIMARY KEY  (
        SESSION_TRANSACTION_HKEY
    ),

    CONSTRAINT UQ_SESSION_TRANSACTION_LINK UNIQUE 
    (
        SESSION_HKEY,
        TRANSACTION_HKEY
    )

);

comment on table SESSION_TRANSACTION_LINK is 'Link between sessions and transactions';
comment on column SESSION_TRANSACTION_LINK.SESSION_TRANSACTION_HKEY is 'Session transaction link key';
comment on column SESSION_TRANSACTION_LINK.SESSION_HKEY is 'Session hkey';
comment on column SESSION_TRANSACTION_LINK.TRANSACTION_HKEY is 'Transaction hkey';
comment on column SESSION_TRANSACTION_LINK.LOAD_DATE is 'Load time';
comment on column SESSION_TRANSACTION_LINK.RECORD_SOURCE is 'Origin';