CREATE TABLE WALLET_TRANSACTION_LINK (
    WALLET_TRANSACTION_HKEY text NOT NULL,
    WALLET_HKEY text NOT NULL,
    TRANSACTION_HKEY text NOT NULL,
    LOAD_DATE TIMESTAMP NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,

    CONSTRAINT PK_WALLET_TRANSACTION_LINK PRIMARY KEY  (
        WALLET_TRANSACTION_HKEY
    ),

    CONSTRAINT UQ_WALLET_TRANSACTION_LINK UNIQUE 
    (
        WALLET_HKEY,
        TRANSACTION_HKEY
    )

);

comment on table WALLET_TRANSACTION_LINK is 'Link between wallets and transactions';
comment on column WALLET_TRANSACTION_LINK.WALLET_TRANSACTION_HKEY is 'Wallet transaction link key';
comment on column WALLET_TRANSACTION_LINK.WALLET_HKEY is 'Wallet hkey';
comment on column WALLET_TRANSACTION_LINK.TRANSACTION_HKEY is 'Transaction hkey';
comment on column WALLET_TRANSACTION_LINK.LOAD_DATE is 'Load time';
comment on column WALLET_TRANSACTION_LINK.RECORD_SOURCE is 'Origin';


