-- PLAYER_HUB
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000001');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000002');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000003');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000004');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000005');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000006');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000007');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000008');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000009');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000010');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000011');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000012');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000013');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000014');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000015');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000016');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000017');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000018');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000019');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000020');

COMMIT;

-- PLAYER_SAT   
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Janez', 'Novak' FROM PLAYER_HUB WHERE PLAYER_ID = '000001';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tomaž', 'Horvat' FROM PLAYER_HUB WHERE PLAYER_ID = '000002';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Marko', 'Kovač' FROM PLAYER_HUB WHERE PLAYER_ID = '000003';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Ana', 'Kovačič' FROM PLAYER_HUB WHERE PLAYER_ID = '000004';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Marija', 'Krajnc' FROM PLAYER_HUB WHERE PLAYER_ID = '000005';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Franc', 'Zupančič' FROM PLAYER_HUB WHERE PLAYER_ID = '000006';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Gregor', 'Potočnik' FROM PLAYER_HUB WHERE PLAYER_ID = '000007';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tina', 'Mlakar' FROM PLAYER_HUB WHERE PLAYER_ID = '000008';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Ema', 'Vidmar' FROM PLAYER_HUB WHERE PLAYER_ID = '000009';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Luka', 'Kos' FROM PLAYER_HUB WHERE PLAYER_ID = '000010';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tilen', 'Golob' FROM PLAYER_HUB WHERE PLAYER_ID = '000011';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Eva', 'Turk' FROM PLAYER_HUB WHERE PLAYER_ID = '000012';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tadeja', 'Kralj' FROM PLAYER_HUB WHERE PLAYER_ID = '000013';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Polona', 'Božič' FROM PLAYER_HUB WHERE PLAYER_ID = '000014';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Gorazd', 'Korošec' FROM PLAYER_HUB WHERE PLAYER_ID = '000015';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Miran', 'Bizjak' FROM PLAYER_HUB WHERE PLAYER_ID = '000016';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Darko', 'Zupan' FROM PLAYER_HUB WHERE PLAYER_ID = '000017';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Rebeka', 'Hribar' FROM PLAYER_HUB WHERE PLAYER_ID = '000018';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Nika', 'Kotnik' FROM PLAYER_HUB WHERE PLAYER_ID = '000019';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Maruša', 'Rozman' FROM PLAYER_HUB WHERE PLAYER_ID = '000020';
