-- PLAYER_HUB
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000001');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000002');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000003');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000004');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000005');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000006');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000007');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000008');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000009');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000010');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000011');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000012');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000013');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000014');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000015');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000016');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000017');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000018');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000019');
INSERT INTO player_hub VALUES(current_timestamp, '127.0.0.1', '000020');

COMMIT;

-- PLAYER_SAT   
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Janez', 'Novak' FROM PLAYER_HUB WHERE PLAYER_ID = '000001';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tomaž', 'Horvat' FROM PLAYER_HUB WHERE PLAYER_ID = '000002';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Marko', 'Kovač' FROM PLAYER_HUB WHERE PLAYER_ID = '000003';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Ana', 'Kovačič' FROM PLAYER_HUB WHERE PLAYER_ID = '000004';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Marija', 'Krajnc' FROM PLAYER_HUB WHERE PLAYER_ID = '000005';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Franc', 'Zupančič' FROM PLAYER_HUB WHERE PLAYER_ID = '000006';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Gregor', 'Potočnik' FROM PLAYER_HUB WHERE PLAYER_ID = '000007';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tina', 'Mlakar' FROM PLAYER_HUB WHERE PLAYER_ID = '000008';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Ema', 'Vidmar' FROM PLAYER_HUB WHERE PLAYER_ID = '000009';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Luka', 'Kos' FROM PLAYER_HUB WHERE PLAYER_ID = '000010';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tilen', 'Golob' FROM PLAYER_HUB WHERE PLAYER_ID = '000011';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Eva', 'Turk' FROM PLAYER_HUB WHERE PLAYER_ID = '000012';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Tadeja', 'Kralj' FROM PLAYER_HUB WHERE PLAYER_ID = '000013';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Polona', 'Božič' FROM PLAYER_HUB WHERE PLAYER_ID = '000014';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Gorazd', 'Korošec' FROM PLAYER_HUB WHERE PLAYER_ID = '000015';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Miran', 'Bizjak' FROM PLAYER_HUB WHERE PLAYER_ID = '000016';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Darko', 'Zupan' FROM PLAYER_HUB WHERE PLAYER_ID = '000017';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Rebeka', 'Hribar' FROM PLAYER_HUB WHERE PLAYER_ID = '000018';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Nika', 'Kotnik' FROM PLAYER_HUB WHERE PLAYER_ID = '000019';
INSERT INTO PLAYER_SAT (PLAYER_HKEY, LOAD_DATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME)
SELECT PLAYER_HKEY, current_timestamp, '127.0.0.1', 'Maruša', 'Rozman' FROM PLAYER_HUB WHERE PLAYER_ID = '000020';

-- SESSION_HUB
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '001');
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '002');
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '003');
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '004');
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '005');
INSERT INTO session_hub VALUES(current_timestamp, '127.0.0.1', '006');

COMMIT;

-- SESSION_SAT
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '001';
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '002';
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '003';
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '004';
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '005';
INSERT INTO SESSION_SAT (SESSION_HKEY, LOAD_DATE, RECORD_SOURCE, SESSION_START_DATE)
SELECT SESSION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute') FROM SESSION_HUB WHERE SESSION_ID = '006';

-- WALLET_HUB
INSERT INTO wallet_hub VALUES(current_timestamp, '127.0.0.1', '001');
INSERT INTO wallet_hub VALUES(current_timestamp, '127.0.0.1', '002');
INSERT INTO wallet_hub VALUES(current_timestamp, '127.0.0.1', '003');
INSERT INTO wallet_hub VALUES(current_timestamp, '127.0.0.1', '004');

COMMIT;

-- WALLET_SAT
INSERT INTO WALLET_SAT (WALLET_HKEY, LOAD_DATE, RECORD_SOURCE, OPENING_BALANCE, CURRENCY_CODE)
SELECT WALLET_HKEY, current_timestamp, '127.0.0.1', 100, 'EUR' FROM WALLET_HUB WHERE WALLET_ID = '001';
INSERT INTO WALLET_SAT (WALLET_HKEY, LOAD_DATE, RECORD_SOURCE, OPENING_BALANCE, CURRENCY_CODE)
SELECT WALLET_HKEY, current_timestamp, '127.0.0.1', 2000, 'CHF' FROM WALLET_HUB WHERE WALLET_ID = '002';
INSERT INTO WALLET_SAT (WALLET_HKEY, LOAD_DATE, RECORD_SOURCE, OPENING_BALANCE, CURRENCY_CODE)
SELECT WALLET_HKEY, current_timestamp, '127.0.0.1', 5000, 'EUR' FROM WALLET_HUB WHERE WALLET_ID = '003';
INSERT INTO WALLET_SAT (WALLET_HKEY, LOAD_DATE, RECORD_SOURCE, OPENING_BALANCE, CURRENCY_CODE)
SELECT WALLET_HKEY, current_timestamp, '127.0.0.1', 1000, 'EUR' FROM WALLET_HUB WHERE WALLET_ID = '004';

-- TRANSACTION_HUB
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-001');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-002');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-003');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-004');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-005');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-006');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-007');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-008');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-009');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-010');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-011');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-012');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-013');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-014');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-015');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-016');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-017');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-018');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-019');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-020');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-021');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-022');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-023');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-024');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-025');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-026');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-027');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-028');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-029');
INSERT INTO transaction_hub VALUES(current_timestamp, '127.0.0.1', '000-030');

COMMIT;

-- TRANSACTION_SAT
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (900 * interval '1 minute'), 100, 100, 100, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-001';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (890 * interval '1 minute'), -200, -200, -200, 'Withdraw' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-002';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (880 * interval '1 minute'), 1000, 1000, 1000, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-003';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (880 * interval '1 minute'), 1000, 1000, 1000, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-004';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (870 * interval '1 minute'), 4000, 4000, 4000, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-005';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (860 * interval '1 minute'), -1000, -1000, -1000, 'Withdraw' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-006';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (850 * interval '1 minute'), -300, -300, -300, 'Withdraw' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-007';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (840 * interval '1 minute'), -700, -700, -700, 'Withdraw' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-008';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (830 * interval '1 minute'), 1000, 1000, 1000, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-009';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (820 * interval '1 minute'), 600, 600, 600, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-010';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (810 * interval '1 minute'), 400, 400, 400, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-011';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (800 * interval '1 minute'), 30, 30, 30, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-012';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (790 * interval '1 minute'), 70, 70, 70, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-013';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (780 * interval '1 minute'), 80, 80, 80, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-014';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (770 * interval '1 minute'), 210, 210, 210, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-015';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (760 * interval '1 minute'), 11, 11, 11, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-016';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (750 * interval '1 minute'), 43, 43, 43, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-017';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (740 * interval '1 minute'), 53, 53, 53, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-018';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (730 * interval '1 minute'), 45, 45, 45, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-019';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (880 * interval '1 minute'), 1000, 1000, 1000, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-020';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (710 * interval '1 minute'), 23, 23, 23, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-021';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (700 * interval '1 minute'), 10, 10, 10, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-022';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (690 * interval '1 minute'), 20, 20, 20, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-023';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (680 * interval '1 minute'), 40, 40, 40, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-024';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (670 * interval '1 minute'), 160, 160, 160, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-025';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (660 * interval '1 minute'), 100, 100, 100, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-026';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (650 * interval '1 minute'), 200, 200, 200, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-027';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (640 * interval '1 minute'), 20, 20, 20, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-028';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (630 * interval '1 minute'), 75, 75, 75, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-029';
INSERT INTO TRANSACTION_SAT (TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE, TRANSACTION_DATE, AMOUNT, OPENING_BALANCE, CLOSING_BALANCE, TRANSACTION_TYPE)
SELECT TRANSACTION_HKEY, current_timestamp, '127.0.0.1', current_timestamp - (620 * interval '1 minute'), 80, 80, 80, 'Bet' FROM TRANSACTION_HUB WHERE TRANSACTION_ID = '000-030';



-- PLAYER_SESSION_LINK
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000001','001')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000001' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000001','002')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000001' AND SESSION_HUB.SESSION_ID = '002';
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000002','003')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000002' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000003','004')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000003' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000003','005')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000003' AND SESSION_HUB.SESSION_ID = '005';
INSERT INTO PLAYER_SESSION_LINK (PLAYER_SESSION_HKEY, PLAYER_HKEY, SESSION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000003','006')), PLAYER_HKEY, SESSION_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN SESSION_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000006' AND SESSION_HUB.SESSION_ID = '006';


-- PLAYER_WALLET_LINK
INSERT INTO PLAYER_WALLET_LINK (PLAYER_WALLET_HKEY, PLAYER_HKEY, WALLET_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000001','001')), PLAYER_HKEY, WALLET_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN WALLET_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000001' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO PLAYER_WALLET_LINK (PLAYER_WALLET_HKEY, PLAYER_HKEY, WALLET_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000002','002')), PLAYER_HKEY, WALLET_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN WALLET_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000002' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO PLAYER_WALLET_LINK (PLAYER_WALLET_HKEY, PLAYER_HKEY, WALLET_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000003','003')), PLAYER_HKEY, WALLET_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN WALLET_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000003' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO PLAYER_WALLET_LINK (PLAYER_WALLET_HKEY, PLAYER_HKEY, WALLET_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000004','004')), PLAYER_HKEY, WALLET_HKEY, current_timestamp, '127.0.0,1' FROM
PLAYER_HUb CROSS JOIN WALLET_HUB
WHERE PLAYER_HUB.PLAYER_ID = '000004' AND WALLET_HUB.WALLET_ID = '004';


-- WALLET_TRANSACTION_LINK
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-001','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-001' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-002','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-002' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-003','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-003' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-004','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-004' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-005','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-005' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-006','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-006' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-007','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-007' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-008','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-008' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-009','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-009' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-0010','001')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-010' AND WALLET_HUB.WALLET_ID = '001';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-011','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-011' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-012','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-012' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-013','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-013' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-014','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-014' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-015','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-015' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-016','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-016' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-017','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-017' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-018','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-018' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-019','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-019' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-020','002')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-020' AND WALLET_HUB.WALLET_ID = '002';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-021','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-021' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-022','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-022' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-023','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-023' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-024','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-024' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-025','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-025' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-026','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-026' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-027','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-027' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-028','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-028' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-029','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-029' AND WALLET_HUB.WALLET_ID = '003';
INSERT INTO WALLET_TRANSACTION_LINK (WALLET_TRANSACTION_HKEY, WALLET_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-030','003')), WALLET_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN WALLET_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-030' AND WALLET_HUB.WALLET_ID = '003';


-- SESSION_TRANSACTION_LINK
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-001','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-001' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-002','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-002' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-003','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-003' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-004','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-004' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-005','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-005' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-006','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-006' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-007','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-007' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-008','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-008' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-009','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-009' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-0010','001')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-010' AND SESSION_HUB.SESSION_ID = '001';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-011','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-011' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-012','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-012' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-013','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-013' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-014','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-014' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-015','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-015' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-016','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-016' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-017','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-017' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-018','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-018' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-019','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-019' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-020','004')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-020' AND SESSION_HUB.SESSION_ID = '004';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-021','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-021' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-022','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-022' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-023','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-023' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-024','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-024' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-025','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-025' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-026','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-026' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-027','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-027' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-028','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-028' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-029','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-029' AND SESSION_HUB.SESSION_ID = '003';
INSERT INTO SESSION_TRANSACTION_LINK (SESSION_TRANSACTION_HKEY, SESSION_HKEY, TRANSACTION_HKEY, LOAD_DATE, RECORD_SOURCE)
SELECT md5(concat('000-030','003')), SESSION_HKEY, TRANSACTION_HKEY, current_timestamp, '127.0.0,1' FROM
TRANSACTION_HUB CROSS JOIN SESSION_HUB
WHERE TRANSACTION_HUB.TRANSACTION_ID = '000-030' AND SESSION_HUB.SESSION_ID = '003';
