/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for CREATE_PLAYER_WALLET transactions
 */
export interface CreatePlayerWallet {
  /**
   * Wallet business number
   */
  walletId: string;
  /**
   * Opening balance at the moment of wallet creation
   */
  openingBalance: number;
  /**
   * Wallet currency
   */
  currencyCode: "EUR" | "GBP" | "CHF";
  /**
   * Player business number
   */
  playerId?: string;
}
