/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for OPEN_PLAYER_SESSION transactions
 */
export interface OpenPlayerSession {
  /**
   * Session business number
   */
  sessionId: string;
  /**
   * Player business number
   */
  playerId: string;
}
