/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for SESSIONS.sql query
 */
export interface Session {
  playerId?: string;
  sessionId?: string;
  firstName?: string;
  lastName?: string;
}
